# Generated by Django 6.0.3 on 2026-03-26 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsize',
            old_name='Product',
            new_name='product',
        ),
    ]
